apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-rag-ai
  namespace: audit-rag-ai
  labels:
    app: audit-rag-ai
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: audit-rag-ai
  template:
    metadata:
      labels:
        app: audit-rag-ai
    spec:
      containers:
      - name: audit-rag-ai
        image: audit-rag-ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: audit-rag-secrets
              key: openrouter-api-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
