apiVersion: v1
kind: Service
metadata:
  name: audit-rag-ai-service
  namespace: audit-rag-ai
  labels:
    app: audit-rag-ai
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: audit-rag-ai
