# ================================================================
# .streamlit/config.toml - CLEANED & PRODUCTION-READY (1.39+)
# ================================================================

[server]
port = 8501
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = true
maxUploadSize = 800
maxMessageSize = 200
runOnSave = false
headless = true
baseUrlPath = ""
cookieSecret = "your-secure-cookie-secret-here"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#ff6b35"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"
base = "light"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
